2022-11-18 10:03:22,567 INFO    MainThread:28680 [wandb_setup.py:_flush():70] setting env: {}
2022-11-18 10:03:22,567 INFO    MainThread:28680 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2022-11-18 10:03:22,567 INFO    MainThread:28680 [wandb_setup.py:_flush():70] setting login settings: {}
2022-11-18 10:03:22,567 INFO    MainThread:28680 [wandb_init.py:_log_setup():303] Logging user logs to D:\code\yolov5-master\classify\wandb\run-20221118_100322-cvkuyy16\logs\debug.log
2022-11-18 10:03:22,567 INFO    MainThread:28680 [wandb_init.py:_log_setup():304] Logging internal logs to D:\code\yolov5-master\classify\wandb\run-20221118_100322-cvkuyy16\logs\debug-internal.log
2022-11-18 10:03:24,481 INFO    MainThread:28680 [wandb_run.py:_console_start():1237] atexit reg
2022-11-18 10:03:24,481 INFO    MainThread:28680 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.WRAP
2022-11-18 10:03:24,481 INFO    MainThread:28680 [wandb_run.py:_redirect():1135] Wrapping output streams.
2022-11-18 10:03:24,482 INFO    MainThread:28680 [wandb_run.py:_redirect():1151] Redirects installed.
2022-11-18 10:03:24,482 INFO    MainThread:28680 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 0
2022-11-18 10:03:24,482 INFO    MainThread:28680 [wandb_run.py:_restore():1179] restore
2022-11-18 10:03:24,847 INFO    MainThread:28680 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "a15f0e1d520546ada49220d36be3d55d"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      total_bytes: 533
    }
  }
}

2022-11-18 10:03:26,850 INFO    MainThread:28680 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "3f73fc747cfe44dcbf4f5e30a6abec46"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 4
    }
    pusher_stats {
      uploaded_bytes: 3791
      total_bytes: 3791
    }
  }
}

2022-11-18 10:03:27,951 INFO    MainThread:28680 [wandb_run.py:_show_files():1536] logging synced files
2022-11-18 10:03:27,952 INFO    MainThread:28680 [internal.py:handle_exit():138] Internal process exited
