2022-11-18 10:03:58,216 INFO    MainThread:29020 [wandb_setup.py:_flush():70] setting env: {}
2022-11-18 10:03:58,216 INFO    MainThread:29020 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2022-11-18 10:03:58,216 INFO    MainThread:29020 [wandb_setup.py:_flush():70] setting login settings: {}
2022-11-18 10:03:58,216 INFO    MainThread:29020 [wandb_init.py:_log_setup():303] Logging user logs to D:\code\yolov5-master\classify\wandb\run-20221118_100358-myvh2ggh\logs\debug.log
2022-11-18 10:03:58,216 INFO    MainThread:29020 [wandb_init.py:_log_setup():304] Logging internal logs to D:\code\yolov5-master\classify\wandb\run-20221118_100358-myvh2ggh\logs\debug-internal.log
2022-11-18 10:04:00,050 INFO    MainThread:29020 [wandb_run.py:_console_start():1237] atexit reg
2022-11-18 10:04:00,051 INFO    MainThread:29020 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.WRAP
2022-11-18 10:04:00,051 INFO    MainThread:29020 [wandb_run.py:_redirect():1135] Wrapping output streams.
2022-11-18 10:04:00,051 INFO    MainThread:29020 [wandb_run.py:_redirect():1151] Redirects installed.
2022-11-18 10:04:00,052 INFO    MainThread:29020 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 0
2022-11-18 10:04:00,052 INFO    MainThread:29020 [wandb_run.py:_restore():1179] restore
2022-11-18 10:04:00,575 INFO    MainThread:29020 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "6769800345c14e21b9ce8ac0a4f40d83"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      total_bytes: 533
    }
  }
}

2022-11-18 10:04:02,585 INFO    MainThread:29020 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "71f9a9b680e4492bbd77bf9ee3ef5388"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 3860
      total_bytes: 3860
    }
  }
}

2022-11-18 10:04:03,681 INFO    MainThread:29020 [wandb_run.py:_show_files():1536] logging synced files
2022-11-18 10:04:03,683 INFO    MainThread:29020 [internal.py:handle_exit():138] Internal process exited
